-- MySQL Script generated by MySQL Workbench
-- Model: Biblioteca Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`leitor`
-- (Antiga tabela Cliente)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`leitor` (
  `id_leitor` INT NOT NULL AUTO_INCREMENT,
  `nome_leitor` VARCHAR(100) NOT NULL,
  `cpf_leitor` CHAR(11) NULL,
  `email_leitor` VARCHAR(100) NULL,
  `telefone_leitor` VARCHAR(20) NULL,
  `endereco_leitor` VARCHAR(100) NULL,
  `dt_nasc_leitor` DATE NULL,
  PRIMARY KEY (`id_leitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`bibliotecario`
-- (Antiga tabela Funcionario)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`bibliotecario` (
  `id_bibliotecario` INT NOT NULL AUTO_INCREMENT,
  `nome_bibliotecario` VARCHAR(100) NOT NULL,
  `telefone_bibliotecario` VARCHAR(20) NULL,
  `email_bibliotecario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_bibliotecario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- (Antiga tabela Marca)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `id_editora` INT NOT NULL AUTO_INCREMENT,
  `nome_editora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_editora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livro`
-- (Antiga tabela Modelo)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo_livro` VARCHAR(100) NOT NULL, -- antigo nome_modelo
  `genero_livro` VARCHAR(45) NULL,      -- antigo cor_modelo
  `ano_publicacao` YEAR NULL,           -- antigo ano_modelo
  `tipo_capa` VARCHAR(45) NULL,         -- antigo tipo_modelo
  `editora_id_editora` INT NOT NULL,
  PRIMARY KEY (`id_livro`, `editora_id_editora`),
  INDEX `fk_livro_editora_idx` (`editora_id_editora` ASC),
  CONSTRAINT `fk_livro_editora`
    FOREIGN KEY (`editora_id_editora`)
    REFERENCES `biblioteca`.`editora` (`id_editora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- (Antiga tabela Venda)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATE NULL,          -- mudado de VARCHAR para DATE (recomendado)
  `data_devolucao` DATE NULL,           -- antigo valor_venda (adaptado)
  `leitor_id_leitor` INT NOT NULL,
  `bibliotecario_id_bibliotecario` INT NOT NULL,
  `livro_id_livro` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`, `leitor_id_leitor`, `bibliotecario_id_bibliotecario`, `livro_id_livro`),
  INDEX `fk_emprestimo_leitor1_idx` (`leitor_id_leitor` ASC),
  INDEX `fk_emprestimo_bibliotecario1_idx` (`bibliotecario_id_bibliotecario` ASC),
  INDEX `fk_emprestimo_livro1_idx` (`livro_id_livro` ASC),
  CONSTRAINT `fk_emprestimo_leitor1`
    FOREIGN KEY (`leitor_id_leitor`)
    REFERENCES `biblioteca`.`leitor` (`id_leitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_bibliotecario1`
    FOREIGN KEY (`bibliotecario_id_bibliotecario`)
    REFERENCES `biblioteca`.`bibliotecario` (`id_bibliotecario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_id_livro`)
    REFERENCES `biblioteca`.`livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;